apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secrets
type: Opaque
data:
  VITE_BREVO_API_KEY: eGtleXNpYi03ZjNmNmJiYzg1ODJkODE3MjkxZWY3Y2FhNWJiZmZkYzllM2RhZmYwYTkwNzkwZWQyYzA5MzJiMmZjMGNiNmQ1LU0zdnh3ZzFtRFBmN2xWRms=

